In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt

In [26]:
df = pd.read_csv('local_data.csv')
df

,1着,2着,3着,予想根拠1,予想根拠2,予想根拠3,予想根拠4,予想根拠5,予想根拠6,予想根拠7,予想根拠8,予想根拠9
0,ジャスティンパレス,ディープボンド,ヒートオンビート,高配当狙い,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,タスティエーラ,スターズオンアース,ソールオリエンス,騎手の勝率,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ドウデュース,ディープボンド,タイトルホルダー,出走馬の前回の着順,開催場所,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,タスティエーラ,タイトルホルダー,ソールオリエンス,勘,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ジャスティンパレス,ドウデュース,ソールオリエンス,騎手の勝率,出走馬の前回のレースの上がり,出走馬の前回のレースの走破時間,開催場所,馬の体重,馬の年齢枠順,展開（他の馬のレールの走り方の特徴）,産駒,調教（追い切り）
5,ディアスティマ,スターズオンアース,ウインマリリン,馬番,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,タスティエーラ,タイトルホルダー,ドウデュース,好きな芸人のよそうにのっかり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ディープボンド,ホウオウエミーズ,ジャスティンパレス,勘,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
horse_analysis = df.drop(columns = ['予想根拠1','予想根拠2', '予想根拠3','予想根拠4', '予想根拠5', '予想根拠6', '予想根拠7', '予想根拠8', '予想根拠9'])
horse_analysis

          1着         2着         3着
0  ジャスティンパレス    ディープボンド   ヒートオンビート
1    タスティエーラ  スターズオンアース   ソールオリエンス
2     ドウデュース    ディープボンド   タイトルホルダー
3    タスティエーラ   タイトルホルダー   ソールオリエンス
4  ジャスティンパレス     ドウデュース   ソールオリエンス
5    ディアスティマ  スターズオンアース    ウインマリリン
6    タスティエーラ   タイトルホルダー     ドウデュース
7    ディープボンド   ホウオウエミーズ  ジャスティンパレス

In [28]:
# 有馬記念の結果
result = ["ドウデュース", "スターズオンアース", "タイトルホルダー"]

# 有馬記念の予想リスト
predictions = [
    ["ジャスティンパレス", "ディープボンド", "ヒートオンビート"],
    ["タスティエーラ", "スターズオンアース", "ソールオリエンス"],
    ["ドウデュース", "ディープボンド", "タイトルホルダー"],
    ["タスティエーラ", "タイトルホルダー", "ソールオリエンス"],
    ["ジャスティンパレス", "ドウデュース", "ソールオリエンス"],
    ["ディアスティマ", "スターズオンアース", "ウインマリリン"],
    ["タスティエーラ", "タイトルホルダー", "ドウデュース"],
    ["ディープボンド", "ホウオウエミーズ", "ジャスティンパレス"]
]

# 1着、2着、3着それぞれの一致数を初期化
first_place_matches = 0
second_place_matches = 0
third_place_matches = 0

# 各予想をチェックし、一致する場合は対応する一致数を増やす
for prediction in predictions:
    if prediction[0] == result[0]:
        first_place_matches += 1
    if prediction[1] == result[1]:
        second_place_matches += 1
    if prediction[2] == result[2]:
        third_place_matches += 1

# 一致率を計算
total_predictions = len(predictions)
first_place_accuracy = first_place_matches / total_predictions
second_place_accuracy = second_place_matches / total_predictions
third_place_accuracy = third_place_matches / total_predictions

# 結果を出力
print(f"1着の一致率: {first_place_accuracy * 100}%")
print(f"2着の一致率: {second_place_accuracy * 100}%")
print(f"3着の一致率: {third_place_accuracy * 100}%")

1着の一致率: 12.5%
2着の一致率: 25.0%
3着の一致率: 12.5%

In [29]:
df_m = pd.read_csv('predict_result/predict_result_arima.csv')
df_m

,race_id,予測結果,馬,人気,オッズ,騎手,馬番,体重,体重変化,性,...,通過順5,着順5,距離5,クラス5,走破時間5,芝・ダート5,天気5,馬場5,平均斤量,騎手の勝率
0,202306050811,0.181758,0,19,NaN,18,NaN,NaN,NaN,0,...,3.000000,10,1800,9,113.3,1,0.0,0,57.2,0.5
1,202306050811,0.101911,1,16,NaN,4,NaN,NaN,NaN,1,...,NaN,1,2400,10,152.3,0,NaN,0,55.9,0.5
2,202306050811,0.035930,3,2,NaN,14,NaN,NaN,NaN,0,...,3.750000,7,2500,10,153.5,0,0.0,0,57.2,0.5
3,202306050811,0.299230,2,11,NaN,11,NaN,NaN,NaN,0,...,5.333333,5,2000,10,118.1,0,0.0,0,57.4,0.5
4,202306050811,0.188493,4,1,NaN,5,NaN,NaN,NaN,1,...,7.750000,1,2400,10,143.9,0,0.0,0,55.6,0.5
5,202306050811,0.476150,5,3,NaN,16,NaN,NaN,NaN,1,...,5.250000,2,2200,6,134.4,0,1.0,1,55.8,0.5
6,202306050811,0.184844,6,5,NaN,9,NaN,NaN,NaN,0,...,5.000000,1,2000,8,122.2,0,1.0,0,56.6,0.5
7,202306050811,0.226968,7,7,NaN,13,NaN,NaN,NaN,0,...,1.000000,9,2500,10,154.1,0,0.0,0,58.0,0.5
8,202306050811,0.221160,8,4,NaN,3,NaN,NaN,NaN,0,...,4.333333,4,1800,8,107.2,0,0.0,0,56.6,0.5
9,202306050811,0.337495,9,17,NaN,6,NaN,NaN,NaN,0,...,1.000000,9,3600,9,227.2,0,1.0,0,57.1,0.5
10,202306050811,0.316236,10,20,NaN,1,NaN,NaN,NaN,0,...,2.000000,5,3000,9,186.6,0,0.0,0,57.8,0.5
11,202306050811,0.105249,12,6,NaN,15,NaN,NaN,NaN,0,...,NaN,19,2400,10,NaN,0,NaN,2,57.5,0.5
12,202306050811,0.034566,11,15,NaN,0,NaN,NaN,NaN,0,...,NaN,2,1900,9,NaN,1,NaN,0,55.6,0.5
13,202306050811,0.105441,13,8,NaN,8,NaN,NaN,NaN,1,...,5.500000,1,1600,8,93.1,0,0.0,1,54.6,0.5
14,202306050811,0.346032,14,12,NaN,7,NaN,NaN,NaN,0,...,6.250000,3,2500,9,151.3,0,0.0,0,57.8,0.5
15,202306050811,0.151014,16,13,NaN,2,NaN,NaN,NaN,0,...,3.750000,3,2200,9,131.5,0,0.0,0,57.2,0.5
16,202306050811,0.409209,15,10,NaN,19,NaN,NaN,NaN,0,...,1.750000,1,2500,5,151.5,0,0.0,0,56.0,0.5
17,202306050811,0.070789,17,14,NaN,17,NaN,NaN,NaN,1,...,13.000000,12,1800,8,108.5,0,0.0,0,54.6,0.5
18,202306050811,0.049695,18,18,NaN,12,NaN,NaN,NaN,0,...,3.000000,4,2000,10,117.8,0,0.0,0,57.6,0.5
19,202306050811,0.126873,19,9,NaN,10,NaN,NaN,NaN,1,...,10.500000,4,2500,9,158.3,0,1.0,3,55.4,0.5

In [30]:
horse_name_to_number = {
  'アイアンバローズ': 0,
  'ウインマリリン': 1,
  'シャフリヤール': 2,
  'ジャスティンパレス': 3,
  'スターズオンアース': 4,
  'スルーセブンシーズ': 5,
  'ソールオリエンス': 6,
  'タイトルホルダー': 7,
  'タスティエーラ': 8,
  'ディアスティマ': 9,
  'ディープボンド': 10,
  'ドゥラエレーデ': 11,
  'ドウデュース': 12,
  'ハーパー': 13,
  'ヒートオンビート': 14,
  'ブローザホーン': 15,
  'プラダリア': 16,
  'ホウオウエミーズ': 17,
  'マテンロウレオ': 18,
  'ライラック': 19,
}

result_number = ['12', '4', '7']
df_m_predictions = ['0', '1', '3']

# 1着、2着、3着それぞれの一致数を初期化
first_place_matches = 0
second_place_matches = 0
third_place_matches = 0

# 各予想をチェックし、一致する場合は対応する一致数を増やす
for prediction in predictions:
    if df_m_predictions[0] == result_number[0]:
        first_place_matches += 1
    if df_m_predictions[1] == result_number[1]:
        second_place_matches += 1
    if df_m_predictions[2] == result_number[2]:
        third_place_matches += 1

# 結果を出力
print(f"1着の一致率: {first_place_matches * 100}%")
print(f"2着の一致率: {second_place_matches * 100}%")
print(f"3着の一致率: {third_place_matches * 100}%")

1着の一致率: 0%
2着の一致率: 0%
3着の一致率: 0%

In [31]:
df

,1着,2着,3着,予想根拠1,予想根拠2,予想根拠3,予想根拠4,予想根拠5,予想根拠6,予想根拠7,予想根拠8,予想根拠9
0,ジャスティンパレス,ディープボンド,ヒートオンビート,高配当狙い,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,タスティエーラ,スターズオンアース,ソールオリエンス,騎手の勝率,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ドウデュース,ディープボンド,タイトルホルダー,出走馬の前回の着順,開催場所,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,タスティエーラ,タイトルホルダー,ソールオリエンス,勘,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ジャスティンパレス,ドウデュース,ソールオリエンス,騎手の勝率,出走馬の前回のレースの上がり,出走馬の前回のレースの走破時間,開催場所,馬の体重,馬の年齢枠順,展開（他の馬のレールの走り方の特徴）,産駒,調教（追い切り）
5,ディアスティマ,スターズオンアース,ウインマリリン,馬番,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,タスティエーラ,タイトルホルダー,ドウデュース,好きな芸人のよそうにのっかり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ディープボンド,ホウオウエミーズ,ジャスティンパレス,勘,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

機械学習による競馬予想はとても難しい。今回アンケートを行った際、予想根拠を答えてもらった。だが、予想根拠のなにがその答えを導き出したのかわからない。もっと分析するときのことを考えてアンケート内容を作るべきだった。予想根拠の何かが分かれば機械学習もうまくできたのではないか。今回、競馬についての知識や、機械学習について知らないことが多いと感じた。背景知識と手段についての知識を増やしていくことにする。